lib/trivia_web/router.ex
defmodule TriviaWeb.Router do
  use TriviaWeb, :router
  use Pow.Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin do
    plug TriviaWeb.EnsureRolePlug, :admin
  end

  scope "/admin", TriviaWeb.Admin, as: :admin do
    pipe_through [:browser, :admin]

    resources "/categories", CategoryController
  end

  scope "/" do
    pipe_through :browser

    pow_routes()
  end

  scope "/", TriviaWeb do
    pipe_through :browser

    resources "/rooms", RoomController, only: [:create], param: "access_code" do
      get "/host", HostController, :index
      get "/play/", PlayerController, :show, as: :play
    end

    post "/join", PlayerController, :create, as: :join

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", TriviaWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TriviaWeb.Telemetry
    end
  end
end

lib/trivia_web/templates/page/host_form.html.eex
<%= form_for @changeset, Routes.room_path(@conn, :create), [as: :room, class: "form"], fn f -> %>
    <h2 class="text-center">Host a Game</h2>

    <% invalid_max = if @changeset.errors[:max_players], do: " is-invalid", else: "" %>
    <% invalid_game = if @changeset.errors[:game_id], do: " is-invalid", else: "" %>

        <div class="form-group">
            <%= label f, :max_players, "Number of Players" %>
            <%= number_input f, :max_players, value: 2, class: "form-control#{invalid_max}", max: 6, min: 2 %>
            <div class="invalid-feedback">
                <%= error_tag f, :max_players %>
            </div>
        </div>
        <div class="form-group">
            <%= label f, :game_id, "Gamemode" %>
            <%= select f, :game_id, @games, prompt: "Select a Gamemode", class: "form-control#{invalid_game}" %>
            <div class="invalid-feedback">
                <%= error_tag f, :game_id %>
            </div>
        </div>
    <button class="btn btn-lg btn-secondary btn-block" type="submit">Create</button>
<% end %>

lib/trivia_web/templates/page/index.html.eex
<section class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-7 col-lg-5">
      <%= render "player_form.html", conn: @conn, changeset: @player_changeset %>
    </div>

    <%= if Pow.Plug.current_user(@conn) do %>
      <div class="d-sm-block col-lg-1 mb-5"></div>
      <div class="col-12 col-md-7 col-lg-5">
        <%= render "host_form.html", conn: @conn, games: @games, changeset: @room_changeset %>
      </div>
    <% end %>
  </div>
</section>

lib/trivia_web/templates/page/player_form.html.eex
<%= form_for @changeset, Routes.join_path(@conn, :create), [as: :player, class: "form"], fn f -> %>
    <h2 class="text-center">Join a Game</h2>

    <% invalid_name = if @changeset.errors[:name], do: " is-invalid", else: "" %>
    <% invalid_code = if @changeset.errors[:access_code], do: " is-invalid", else: "" %>

    <div class="form-group">
        <%= label f, :name, "Name" %>
        <%= text_input f, :name, class: "form-control#{invalid_name}", placeholder: "Enter your name" %>
        <div class="invalid-feedback">
            <%= error_tag f, :name %>
        </div>
    </div>
    <div class="form-group">
        <%= label f, :access_code, "Room Code" %>
        <%= text_input f, :access_code, class: "form-control#{invalid_code}", placeholder: "Enter 4-letter code" %>
        <div class="invalid-feedback">
            <%= error_tag f, :access_code %>
        </div>
    </div>
    <button class="btn btn-lg btn-secondary btn-block" type="submit">Play</button>
<% end %>