lib/trivia_web/router.ex
defmodule TriviaWeb.Router do
  use TriviaWeb, :router
  use Pow.Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin do
    plug TriviaWeb.EnsureRolePlug, :admin
  end

  scope "/admin", TriviaWeb.Admin, as: :admin do
    pipe_through [:browser, :admin]

    resources "/categories", CategoryController
  end

  scope "/" do
    pipe_through :browser

    pow_routes()
  end

  scope "/", TriviaWeb do
    pipe_through :browser

    resources "/rooms", RoomController, only: [:create], param: "access_code" do
      get "/host", HostController, :index
      get "/play/", PlayerController, :show, as: :play
    end

    post "/join", PlayerController, :create, as: :join

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", TriviaWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TriviaWeb.Telemetry
    end
  end
end

lib/trivia_web/views/layout_view.ex
defmodule TriviaWeb.LayoutView do
  use TriviaWeb, :view
end

lib/trivia_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>ADZGAMES TRIVIA</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light fixed-top" id="navbar">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-brand" id="brand">
        <a href="/"><img src="<%= Routes.static_path(@conn, "/images/adzgames.svg") %>" width="35" class="d-inline-block align-top" alt=""></a>
      </div>
      <div class="navbar-collapse collapse w-100" id="navbarMenu">
        <ul class="navbar-nav w-100 justify-content-center text-center">
          <%= if Pow.Plug.current_user(@conn) do %>
          <li class="nav-item">
                          <%= link "Categories", to: Routes.admin_category_path(@conn, :index), class: "nav-link" %>
          </li>
            <li class="nav-item">
              <%= link "Sign out", to: Routes.pow_session_path(@conn, :delete), method: :delete, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link "Sign in", to: Routes.pow_session_path(@conn, :new), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link "Register", to: Routes.pow_registration_path(@conn, :new), class: "nav-link" %>
            </li>
          <% end %>
      </div>
    </nav>
    <main role="main">
      <div class="container">
        <div class="row justify-content-center">
          <%= Enum.map(get_flash(@conn), fn {flash_key, flash_message} -> %>
            <% alert_class = if (flash_key == "error"), do: 'danger', else: flash_key %>
            <%= if (flash_message) do %>
              <div class="alert alert-<%= alert_class %>"><%= flash_message %></div>
            <% end %>
          <% end) %>
        </div>
      </div>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

lib/trivia_web/templates/layout/host.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>ADZGAMES TRIVIA</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <%= render @view_module, @view_template, assigns %>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/host.js") %>"></script>
  </body>
</html>

lib/trivia_web/templates/layout/player.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>ADZGAMES TRIVIA</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <%= render @view_module, @view_template, assigns %>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/player.js") %>"></script>
  </body>
</html>